### ISSUE TITLE
How to get the sampling points

### ISSUE THREAD

**Issue by chendagui16** [msracver/Deformable-ConvNets#10]
I note that you have plotted the sampling red locations for different activation units, which are very helpful for understanding deformable convents, but I wonder how to get the sampling points? How can I find the location corresponds to deformable filter?

**Comment by Orpine** [comment]
Our members are working on visualization tools currently. You can get sampling point by retrieve offset from offset convolution's output by your own. Please refer our deformable convolution and deformable im2col to see how we utilize offset map.

**Comment by chendagui16** [comment]
@Orpine However, I cannot understand Why does there are only these sampling points corresponding to the deformable filter? If I backward one deformable filter at high layer, I would get a large receptive field instead of these red points. What does these red points mean?

**Comment by Orpine** [comment]
@chendagui16  We update our code and give demos about showing deformable conv / deformable psroipooling sampling, please have a look.

**Comment by chendagui16** [comment]
@Orpine Very thanks to your update!

**Comment by gzhcv** [comment]
@YuwenXiong @chendagui16 Sorry for that i did not find the visualization tools used for plotting the sampling points, could you tell me where is it?  One more question,  i trained a Deformable ConvNets for Classification task and have gained accurancy. Then i extract the offset value, and find that there is a little offset value nearly 100. This result also bothered me, is it normal?

**Comment by kirkzZ** [comment]
@gzhcv   Have you  plotting the sampling points,could you help me?
