### ISSUE TITLE
Which train sets were models on OneDrive trained on?

### ISSUE THREAD

**Issue by Rizhiy** [msracver/Deformable-ConvNets#104]
Could you please specify which MS COCO sets were used to train models which are on OneDrive?

More specifically have you used val2017 for training?

**Comment by Oh233** [comment]
COCO team has updated their name, so the new-old name mapping should be:
COCO train2014 + COCO val2014 - COCO minival (e.g. COCO trainval35k) = COCO train2017
COCO minival = COCO val2017

For deformable R-FCN, deformable Faster RCNN, we use COCOtrainval2014 as training data and test on COCO test-dev. Therefore, COCO val2017 is used for training.

For deformable FPN, we use COCO trainval35k as training data and test on COCO minival (COCO val2017). Therefore, COCO val 2017 is not used for training.
