### ISSUE TITLE
train log seems good, but testing result is very bad

### ISSUE THREAD

**Issue by xueyoo** [msracver/Deformable-ConvNets#108]
when training the RPN with my own dataset, the log shows:
Epoch[6] Batch [1500]	Speed: 21.19 samples/sec	Train-RPNAcc=0.994731,	RPNLogLoss=0.017133,	RPNL1Loss=0.002498,	RCNNAcc=0.895507,	RCNNLogLoss=1.381965,	RCNNL1Loss=0.211760

but the testing for the result is very bad
Writing 3_LG_1 VOC results file
Writing 3_LS_2 VOC results file
Writing 3_LS_3 VOC results file
VOC07 metric? Y
AP for 3_LG_1 = 0.0049
AP for 3_LS_2 = 0.0117
AP for 3_LS_3 = 0.0014
Mean AP@0.5 = 0.0060
AP for 3_LG_1 = 0.0008
AP for 3_LS_2 = 0.0002
AP for 3_LS_3 = 0.0001
Mean AP@0.7 = 0.0004

is there any configure file need to update when I use my own data?

**Comment by yajieC** [comment]
I have a similar problem , when i train VOC ,there is a good result , however the evaluation result is terrible.I wonder how you solve this problem?

**Comment by zchrissirhcz** [comment]
@xueyoo @yajieC Do you check whether the testing use an existing result file or do test on each image? If it the former, it may be caused by cached file.

**Comment by liyaochong** [comment]
Do you solve this problem?   Can you share the solution with me?   Thankyou a lot!

**Comment by zchrissirhcz** [comment]
We can only do inference by specifing that do not use cached file:

```python
python ./experiments/faster_rcnn/rcnn_test.py --cfg ./experiments/faster_rcnn/cfgs/resnet_v1_101_voc07_rcnn_end2.end.yml --ignore_cache
```

**Comment by yajieC** [comment]
I don't precisely know why would the problem come.Probably,my training procedure broke sometimes causing this problem.And it is not caused by  the cached files.I might have solved this problem by modify the .yaml , i adjust the warmup_step from 1000 to 4000.

**Comment by liyaochong** [comment]
Thakyou for your answer,but I have already adjust the warmup_step from 1000 to 4000. And I have changed the training image as the test image.But the issue is still exist. Is my dataset too small?

**Comment by bitwangdan** [comment]
hi, i have a simliar problem too, can someone solved this problem?
