### ISSUE TITLE
is there any description to generate pretraining model?

### ISSUE THREAD

**Issue by xueyoo** [msracver/Deformable-ConvNets#111]
hi everybody, 
I am using mxnet to detect new objects (which is fully different with imagenet object)
is there any steps to generate the pretrained resnet101 models?

thanks

**Comment by Rizhiy** [comment]
AFAIK, they converted their resnet101 model from caffe, so it will be difficult to generate (also are you sure you have enough data to train them from scratch?).

Have you tried just training the detector using their model? The number of cases where you would need to retrain the feature extractor is very small.

**Comment by xueyoo** [comment]
thanks for your replay
provided model is successfully to training and detect object, I guess there is some super parameter need to update to fit my dataset.

**Comment by Rizhiy** [comment]
To fit your dataset you will need to write a handler to your dataset similar to the ones in `lib/dataset/' and update the config.
