### ISSUE TITLE
Where to get ImageNet-pretrained Deformable ResNet-v1-101 model ?

### ISSUE THREAD

**Issue by chowkamlee81** [msracver/Deformable-ConvNets#116]
I need to have ImageNet-pretrained Deformable ResNet-v1-101 model... where can i get because only ResNet-V1-101 model is available as resnet_v1_101-0000.params. 

I would like to have for deformable model.. Kindly let me know.

**Comment by YuwenXiong** [comment]
We don't apply Deformable ConvNets to ImageNet classification, so sorry, no such model.

**Comment by chowkamlee81** [comment]
To train deeplab deformable CNN segmentation, how to get pretrained model? How it will run

**Comment by YuwenXiong** [comment]
Just use ResNet-V1-101 model as pretrained model, please refer our readme.

**Comment by chowkamlee81** [comment]
Thanks got the solution as per your advice
