### ISSUE TITLE
Question of multithreading in PrefetchingIter.py

### ISSUE THREAD

**Issue by xmyqsh** [msracver/Deformable-ConvNets#118]
Hi,
I notice the 
[https://github.com/msracver/Deformable-ConvNets/blob/master/lib/utils/PrefetchingIter.py#L41](https://github.com/msracver/Deformable-ConvNets/blob/master/lib/utils/PrefetchingIter.py#L41) and [https://github.com/msracver/Deformable-ConvNets/blob/master/lib/utils/PrefetchingIter.py#L46-#L47](https://github.com/msracver/Deformable-ConvNets/blob/master/lib/utils/PrefetchingIter.py#L46-#L47)  in PrefetchingIter.py only support one thread for one DataIter in the Productor-Consumer Model, which is not efficient enough for my application.

How can I modify this to support multi-threads for one DataIter?

**Comment by YuwenXiong** [comment]
You can refer https://github.com/TuSimple/TuSimple-DUC/blob/master/tusimple_duc/core/cityscapes_loader.py

**Comment by xmyqsh** [comment]
Another good work!
Thanks a lot!
