### ISSUE TITLE
NameError: name 'resnet_v1_101_rfcn_light' is not defined

### ISSUE THREAD

**Issue by moyans** [msracver/Deformable-ConvNets#120]
how can i fix this erro  "NameError: name 'resnet_v1_101_rfcn_light' is not defined"

**Comment by Oh233** [comment]
@terrychenism

**Comment by terrychenism** [comment]
@moyans 
add https://github.com/terrychenism/Deformable-ConvNets/blob/master/rfcn/symbols/__init__.py#L3

**Comment by moyans** [comment]
3Q_Q3
