### ISSUE TITLE
Poor results for other imagenet pretrained model

### ISSUE THREAD

**Issue by aliceyayunji** [msracver/Deformable-ConvNets#121]
@YuwenXiong 

I've tried resnet-v2 and resnext model to replace the res-v1-101 model, but always get poor results.
For the resnext: 
I've download the model from http://data.mxnet.io/models/imagenet/ and train the basic faster rcnn without deformable, but the first epoch mscoco test value is poor, (AP) @[ IoU=0.50:0.95 ] = 0.153,  the basic resnet-v1-101 val is 0.219.

Then I tried to remove the data bn layer, still results poor :
Epoch 1 | 14.8 
Epoch 2 | 15
Epoch 3 | 15.3
Epoch 4 | 15.3

Then I think maybe the model trained by mxnet is not good ,so I converted the model from caffe, but still doesn't work.
Epoch 1 | 14.2 
Epoch 2 | 16.9
Epoch 3 | 18
Epoch 4 | 18.5
Epoch 5 | 19.2
Epoch 6 | 20.1

Is there any points you know, that I've ignored, so that the results are poor.

ps. I've trained the basic faster rcnn, and get the same results you've posted on the page. And Fix the conv1 and stage 1 layers' weights.

**Comment by xueyoo** [comment]
yes, I have got the poor result too,  even though the Train-RPNAcc is large than 0.99, and  RCNNAcc is large than 0.97

**Comment by Oh233** [comment]
1) Did you fix the bn statistics?
2) Did you use dilated convolution && adjust the feature stride?

**Comment by aliceyayunji** [comment]
@Oh233 

Yes, I fixed the all the bn layers with set the Config file with beta and gamma.
I didn't use  dilated convolution, so I trained the network again, results improved but still not good.
I think it's not the key point lead to the poor results.

Epoch 1 | 14.3 
Epoch 2 | 17.8
Epoch 3 | 19
Epoch 4 | 19.8
Epoch 5 | 20.5

The attach files are my configs, symbol implement, network graph:

[resnext_101_coco_rcnn_end2end.yaml.txt](https://github.com/msracver/Deformable-ConvNets/files/1541249/resnext_101_coco_rcnn_end2end.yaml.txt)
[resnext_101_rcnn.py.txt](https://github.com/msracver/Deformable-ConvNets/files/1541250/resnext_101_rcnn.py.txt)
[rcnn_net_params.txt](https://github.com/msracver/Deformable-ConvNets/files/1541246/rcnn_net_params.txt)
[rcnn_resnext_101.pdf](https://github.com/msracver/Deformable-ConvNets/files/1541248/rcnn_resnext_101.pdf)

**Comment by aliceyayunji** [comment]
@Oh233  

Finally I train the faster rcnn with resnext network well, the problem were:
1. The parameters of the BN layer should set exactly the same as the pretrained model set, eg. the esp val is 0.0001 but the val for resnet-v1-101 is 1e-5. 
2. The parameters to fix is the main problem. In the code, it's "if prefix in name" way, it lead to fix more layers then I expected.

**Comment by Oh233** [comment]
I see. Thanks for your feedback.

**Comment by StOnEGiggity** [comment]
@aliceyayunji 
Hi, would you mind sharing more details about the second point. Similar result in resnet101-v2 and i change eps to 2e-5 corresponding to pretrained model. I fixed conv0 and stage1 conv 's weight and bn gamma and beta
