### ISSUE TITLE
About Light head Errro 

### ISSUE THREAD

**Issue by moyans** [msracver/Deformable-ConvNets#125]
@terrychenism when I'm training get this erro,

Epoch[0] Batch [16100]	Speed: 4.03 samples/sec	Train-RPNAcc=0.925120,	RPNLogLoss=0.242852,	RPNL1Loss=0.065234,	RCNNAcc=0.804096,	RCNNLogLoss=0.977945,	RCNNL1Loss=0.587750,	
Epoch[0] Batch [16200]	Speed: 4.03 samples/sec	Train-RPNAcc=0.925266,	RPNLogLoss=0.242467,	RPNL1Loss=0.065175,	RCNNAcc=0.803835,	RCNNLogLoss=0.978509,	RCNNL1Loss=0.588405,	
Epoch[0] Batch [16300]	Speed: 4.03 samples/sec	Train-RPNAcc=0.925351,	RPNLogLoss=0.242249,	RPNL1Loss=0.065088,	RCNNAcc=0.803694,	RCNNLogLoss=0.978893,	RCNNL1Loss=0.588792,	
Epoch[0] Batch [16400]	Speed: 4.05 samples/sec	Train-RPNAcc=0.925493,	RPNLogLoss=0.241871,	RPNL1Loss=0.064978,	RCNNAcc=0.803601,	RCNNLogLoss=0.978824,	RCNNL1Loss=0.588956,	
Epoch[0] Batch [16500]	Speed: 4.03 samples/sec	Train-RPNAcc=0.925555,	RPNLogLoss=0.241684,	RPNL1Loss=0.064945,	RCNNAcc=0.803539,	RCNNLogLoss=0.978706,	RCNNL1Loss=0.588927,	
Traceback (most recent call last):
  File "experiments/rfcn/rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 167, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 160, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "experiments/rfcn/../../rfcn/core/module.py", line 996, in fit
    callback(epoch, self.symbol, arg_params, aux_params)
  File "experiments/rfcn/../../rfcn/core/callback.py", line 51, in _callback
    weight = arg['rfcn_bbox_weight']
KeyError: 'rfcn_bbox_weight'

**Comment by Tveek** [comment]
replace the _callback function in do_checkpoint by following code
`arg['bbox_pred_weight_test'] = (arg['bbox_pred_weight'].T * mx.nd.array(stds)).T
        arg['bbox_pred_bias_test'] = arg['bbox_pred_bias'] * mx.nd.array(stds) + mx.nd.array(means)
        mx.model.save_checkpoint(prefix, iter_no + 1, sym, arg, aux)
        arg.pop('bbox_pred_weight_test')
        arg.pop('bbox_pred_bias_test')`

**Comment by Rizhiy** [comment]
@moyans Does Light-head work for you?

**Comment by shesung** [comment]
the custom do_checkpoint function seems to be useless. 

setting epoch_end_callback with mx.callback.do_checkpoint in train_end2end.py also works.

**Comment by Rizhiy** [comment]
@shesung Have you managed to train light-head on coco? I tried, but got very bad results (0.25mmAP).

**Comment by qtaozhou1994** [comment]
@Tveek hello,excuse me ,i don't understand the operation of 'arg['bbox_pred_weight_test']',
maybe arg['bbox_pred_weight_test']  for test? Could I comment them?
