### ISSUE TITLE
how to utilize fpn on deformable convnets 

### ISSUE THREAD

**Issue by LeonJWH** [msracver/Deformable-ConvNets#126]
I want to use fpn to generate muti-scale region proposal with resnet101, it is illustrated in your slides [(http://presentations.cocodataset.org/COCO17-Detect-MSRA.pdf)](url)
But except convolution layers in **res5**(between **conv4** and  **conv5**), I wonder which specific convolution layers defore **conv3** and **conv4** should be changed to deformable convolution. 
Can you give me some advices?

**Comment by Oh233** [comment]
You may refer to the newest version, which contains deformable version of FPN.

**Comment by LeonJWH** [comment]
OK, I see it, thank you very much.
