### ISSUE TITLE
How to calculate the num_filter and num_group

### ISSUE THREAD

**Issue by KaiyuYue** [msracver/Deformable-ConvNets#128]
Hi, guys:

I am confused about the method to calculate the number of filter in offset layer and the number of group in deformable convolution layer. Can you explain that why is 72 num_filter in offset layers and the relationships between these two hyper-parameters?

Many thanks.

**Comment by Oh233** [comment]
72 = 3 x 3 x 2 x 4 = kernel_w x kernel_h x num_coordinates x num_deformable_group. 
The number of coordinates is always 2 (x offset, y offset). Kernel_w and Kernel_h is the kernel size of the deformable convolutional layer.

**Comment by KaiyuYue** [comment]
Thanks.
