### ISSUE TITLE
Can't see the accuracy improve after trainning rfcn_dcn after 7 epoch compared with epoch 1

### ISSUE THREAD

**Issue by kevin8new** [msracver/Deformable-ConvNets#133]
I am running the dcn on Ubuntu, when I try to train and test the rfcn_dcn, I firstly train the model end2end for epoch1 on voc and I get an accuracy.

After that, I start a new training, using the cfg file you provide to train for 7 epochs, after I got the model after training. The test result is exactly the same with the one after epoch 1. I guess that the program didn't use the newest generated model parameters to test and use the cache from the test after epoch 1. Can someone help me find the problem and provide a solution.

Thanks a lot!!!!!

**Comment by Oh233** [comment]
Please make sure the 'test_epoch' config in your yaml file is correct.

**Comment by kevin8new** [comment]
I have solved the problem.
You have to delete the .pkl file in the output path, then the code will run the test again from the beginning.
@Oh233

**Comment by Oh233** [comment]
@kevin8new You can simply add --ignore_cache to re-evaluated the results.

**Comment by kevin8new** [comment]
Get it! Thx!
@Oh233
