### ISSUE TITLE
Can't see the evaluation results after test 

### ISSUE THREAD

**Issue by kevin8new** [msracver/Deformable-ConvNets#136]
Hi, 
I run the faster_rcnn_dcn network on coco, and after training and testing, there are no output results, such as mAP. The only texts on my screen are as follows:
...
testing 20286/20288 data 0.4617s net 0.2470s post 0.0202s
testing 20288/20288 data 0.4617s net 0.2470s post 0.0203s
Writing results json to ./output/rcnn/coco/resnet_v1_101_coco_trainval_rcnn_dcn_end2end/test-dev2015/results/detections_test-dev2015_results.json 

After that, there is nothing. 

And I try to find something in the log file, but there is nothing valuable only with:
...
2018-01-02 11:51:41,899 testing 20288/20288 data 0.4617s net 0.2470s post 0.0203s
2018-01-02 11:54:00,005 evaluate detections: 
None

When I run the same network on the voc dataset, the output results are directly showed on my screen, like the mAP value.

I am new to these field, can anyone help me find out what happen? Thanks a lot!

**Comment by Oh233** [comment]
For MS COCO models, the test-dev dataset has no public annotation and can only be evaluated on the **codalab** evaluation server. And some of our model is trained on train+val and test on test-dev, therefore you must submit the json file to the server to get a mAP results. (More details in: https://github.com/msracver/Deformable-ConvNets/issues/104).

I would suggest you change the image_set to be train2014+valminusminival2014 and test_image_set to be minival2014. In such case you can evaluate locally. (You may also refer to https://github.com/msracver/Deformable-ConvNets/blob/master/experiments/fpn/cfgs/resnet_v1_101_coco_trainval_fpn_dcn_end2end_ohem.yaml for detail setting)

**Comment by kevin8new** [comment]
Thanks a lot!

So according to the [#104](https://github.com/msracver/Deformable-ConvNets/issues/104),  should I train on COCO train2017 and test on COCO val2017 if I want to evaluate locally?

If the answer is not, where can I download the minival2014 and valminusminival2014 image sets and corresponding annotations?

Sorry for the basic questions, thanks for your time!

**Comment by Oh233** [comment]
Please check https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/README.md. I will update the readme when I have time.
