### ISSUE TITLE
What does it mean of dilate/rate in your Deformable convolution?

### ISSUE THREAD

**Issue by John1231983** [msracver/Deformable-ConvNets#140]
Hello, thanks your great work. I am reading the deeplab and found the line

>res5b_branch2b = mx.contrib.symbol.DeformableConvolution(name='res5b_branch2b', data=res5b_branch2a_relu, offset=res5b_branch2b_offset,num_filter=512, pad=(2, 2), kernel=(3, 3), num_deformable_group=1, stride=(1, 1), **dilate=(2, 2)**, no_bias=True)

I understand about dilate/rate in Dilated convolution which sparse the convolution kernel and put zero in between. However, I did not find your explanation about dilate in your proposed convolution. Could you tell me what is it? In my opinion, it may be first sparse convolution kernel like dilated convolution, then apply your deformable convolution on the sparse kernel. Am I right?

![image](https://user-images.githubusercontent.com/24875971/34555203-df202334-f173-11e7-8912-dde2bde28e94.png)

**Comment by YuwenXiong** [comment]
Yes, you are right.

**Comment by John1231983** [comment]
Thanks @YuwenXiong . I have one more question related to dilation. When you use dilation/rate is 2 in deformable convolution, Why did not use same rate (rate=2) in the offset. In your implementation, it looks

```
res5c_branch2b_offset = mx.symbol.Convolution(name='res5c_branch2b_offset', .., pad=(1, 1), kernel=(3, 3), stride=(1, 1), ...)
res5c_branch2b = mx.contrib.symbol.DeformableConvolution(name='res5c_branch2b', ...offset=res5c_branch2b_offset,...,dilate=(2, 2), no_bias=True)
```
In my opinion, it must be

`res5c_branch2b_offset = mx.symbol.Convolution(..., pad=(1, 1), kernel=(3, 3), stride=(1, 1), rate=(2,2)..)`
