### ISSUE TITLE
Can I use cuda7.5 rather than cuda8.0

### ISSUE THREAD

**Issue by zhFuECL** [msracver/Deformable-ConvNets#15]
Does anybody try cuda7.5? Because the GPU driver of our server can't allow me to install cuda8.0.

**Comment by Orpine** [comment]
I think it is OK. Just compile a MXNet w/ cuda 7.5.

**Comment by zhFuECL** [comment]
@Orpine Finally I installed the environment successfully(Cuda7.5, Cudnn5.1.3, Python2.7.13 by anaconda). But I found another problem that when I run  `python ./rfcn/demo.py` , I had the following error:
> Segmentation fault (core dumped)

Could you have me?

**Comment by mursalal** [comment]
@Orpine how can i do step 3 from Installation:

> Copy operators in ./rfcn/operator_cxx to $(YOUR_MXNET_FOLDER)/src/operator/contrib and recompile MXNet.

 if I use mxnet in virtualenv?

**Comment by zhFuECL** [comment]
@Orpine I solved the problem by https://github.com/msracver/Deformable-ConvNets/issues/3#issuecomment-301701062

**Comment by baiyancheng20** [comment]
@zhFuECL How did you solve the problem? Could you give a detail?

**Comment by zhFuECL** [comment]
@baiyancheng20  I gave the solution in the last comment.

**Comment by baiyancheng20** [comment]
@zhFuECL could you give a detail since there are many suggestions in https://github.com/msracver/Deformable-ConvNets/issues/3#issuecomment-301701062
