### ISSUE TITLE
Hardcoded number of anchors in pyramid_proposal.

### ISSUE THREAD

**Issue by Rizhiy** [msracver/Deformable-ConvNets#156]
https://github.com/msracver/Deformable-ConvNets/blob/0bb36278e7e1c007bf255927f1a773bcb31328df/fpn/operator_py/pyramid_proposal.py#L25-L27

Hardcoded constants are not a good idea, perhaps change line 27 to:
```python
	self._num_anchors = config.network.NUM_ANCHORS
```
or even better:
```python
	self._num_anchors = len(self._scales) * len(self._ratios)
```

**Comment by Oh233** [comment]
You are right. This is a careless bug. I fixed it in last commit.
