### ISSUE TITLE
Could not find a version that satisfies the requirement mxnet-cu80==0.12.0b20171027 

### ISSUE THREAD

**Issue by xiadeye** [msracver/Deformable-ConvNets#159]
cannot install mxnet-cu80==0.12.0b20171027
output:
Could not find a version that satisfies the requirement mxnet-cu80==0.12.0b20171027 (from versions: 0.9.3a0, 0.9.3a1, 0.9.3a3, 0.9.5, 0.9.5.post1, 0.9.5.post2, 0.9.5.post3, 0.10.0, 0.10.0.post2, 0.11.0b20170815, 0.11.0b20170819, 0.11.0, 0.11.1b20170826, 0.11.1b20170902, 0.11.1b20170909, 0.11.1b20170916, 0.11.1b20170930, 0.11.1b20171007, 0.12.0b20171021, 0.12.0b20171028, 0.12.0, 0.12.1b20171104, 0.12.1b20171117, 0.12.1b20171124, 0.12.1b20171201, 0.12.1, 1.0.0b20171215, 1.0.0b20171222, 1.0.0, 1.0.0.post0, 1.0.0.post1, 1.0.0.post2, 1.0.0.post4, 1.0.1b20180105, 1.0.1b20180123, 1.0.1b20180129, 1.0.1b20180205, 1.1.0b20180212, 1.1.0b20180219, 1.1.0, 1.2.0b20180226, 1.2.0b20180227)
No matching distribution found for mxnet-cu80==0.12.0b20171027

**Comment by shanYanGuan** [comment]
Have you  solved this problem？

**Comment by YueXiNPU** [comment]
+1 Have you solved this problem？

**Comment by chinakook** [comment]
Just use 1.1.0 . It’s better

**Comment by xiadeye** [comment]
yes,I just use 0.11.0.
I ask the question because whatever mx version I installed encountered problem,at first I thought I need the specify version,but finally I found it's the acconda problem.I uninstalled conda and it worked ok.
