### ISSUE TITLE
Odds Error in training FPN using my own dataset

### ISSUE THREAD

**Issue by HoracceFeng** [msracver/Deformable-ConvNets#162]
Hi, recently I run the FPN using my dataset and get errors about the ROI result, below is what I have met:

Everytime I run the code, it will stop before running 1 epoch with the error claiming:
   "Incompatible tensor ... expect [2001, 256, 7, 7], got [2002,256,7,7]"
Then I find that in "fpn/operator_py/roi_pooling_layer.oy", when running the forward() function, 31 line, I got an error when calculating this:
        w = rois[:3] - roi[:1] + 1
it should be a positive value, but sometime I got negative.

So it may be my xml error, I think. But then I check my xml, no error was found. Actually, I have used this dataset to run in several models successfully, like yolo, RFB, SSD. 

Anyone can help me fix it? I have stucked here more than 2 days.
Thank you!

**Comment by HoracceFeng** [comment]
New question: how can I continue my training using the previous .param file? It is very inconvenient cause sometimes the machine have to restart, and when i restart my training, the model will be trained again.

BTW, the question above is fix. Anyone who have this issue please try this:
https://github.com/msracver/Deformable-ConvNets/issues/35

**Comment by Karthik-Suresh93** [comment]
@HoracceFeng how did you solve the incompatible shapes problem? Please let me know
