### ISSUE TITLE
AssertionError: conv1_weight not initialized

### ISSUE THREAD

**Issue by xielele** [msracver/Deformable-ConvNets#172]
When I run the script of  python experiments/rfcn/rfcn_end2end_train_test.py --cfg experiments/rfcn/cfgs/resnet_v1_101_voc0712_rfcn_end2end_ohem.yaml , I got the error: 
 File "experiments/rfcn/rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 164, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 102, in train_net
    sym_instance.check_parameter_shapes(arg_params, aux_params, data_shape_dict)
  File "experiments/rfcn/../../rfcn/../lib/utils/symbol.py", line 47, in check_parameter_shapes
    assert k in arg_params, k + ' not initialized'
AssertionError: conv1_weight not initialized

I used the resnet-101 pretrained model downloaded from http://data.mxnet.io/models/imagenet/resnet/101-layers/.

Can anyone helps fix this problem?

**Comment by maozezhong** [comment]
Hello, how do you fix this problem? @xielele

**Comment by alashkari** [comment]
@maozezhong You must download the pre-trained ResNet-v1-101 model manually from [OneDrive](https://1drv.ms/u/s!Am-5JzdW2XHzhqMEtxf1Ciym8uZ8sg), not from the MXNet model zoo.
