### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by mursalal** [msracver/Deformable-ConvNets#18]
`Traceback (most recent call last):
  File "./rfcn/demo.py", line 129, in <module>
    main()
  File "./rfcn/demo.py", line 50, in main
    sym = sym_instance.get_symbol(config, is_train=False)
  File "/mnt/Deformable-ConvNets/rfcn/symbols/resnet_v1_101_rfcn_dcn.py", line 725, in get_symbol
    relu1 = self.get_resnet_v1_conv5(conv_feat)
  File "/mnt/Deformable-ConvNets/rfcn/symbols/resnet_v1_101_rfcn_dcn.py", line 633, in get_resnet_v1_conv5
    res5a_branch2b = mx.contrib.symbol.DeformableConvolution(name='res5a_branch2b', data=res5a_branch2a_relu, offset=res5a_branch2b_offset,
AttributeError: 'module' object has no attribute 'DeformableConvolution'`

**Comment by Oh233** [comment]
This is because either 
you forget to copy the operators to your MXNet folder
or you copy to the wrong path
or you forget to re-compile
or you install the wrong MXNet

**Comment by mursalal** [comment]
@Oh233 I installed MXNet from http://mxnet.io/get_started/install.html.
I copied operators by:

`cp -r ./rfcn/operator_cxx/* ../mxnet/src/operator/contrib`

then I recompiled mxnet.

I followed installation guide from repo.

There is commands that I used:

`git clone https://github.com/msracver/Deformable-ConvNets.git`

`cd Deformable-ConvNets`

`sh ./init.sh`

`cd ..`

`git clone --recursive https://github.com/dmlc/mxnet`

`cd mxnet`

`make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1`

`cd python`

`sudo python setup.py install`

`cd ../../`  from mxnet/python to mxnet/../

`cd Deformable-ConvNets`

`cp -r ./rfcn/operator_cxx/* ../mxnet/src/operator/contrib`

`cd ../mxnet`

`make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1`

`cd ../Deformable-ConvNets`

Downloaded model from OneDrive

`python ./rfcn/demo.py`


I also tried compile MXNet on commit 62ecb60. Same error

**Comment by Oh233** [comment]
If those are exactly the commands you used, then you forgot to ```sudo python setup.py install``` after recompiling.

**Comment by mursalal** [comment]
@Oh233 you are right! Thank you. One more question: I am using Ubuntu 16.04 without GUI. I think because of this I am getting

`File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3784, in cla
    ret = gca().cla()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

How solve it?

**Comment by miraclewkf** [comment]
I have the same problem after `sudo python setup.py install`. What you mean you install the wrong MXNet?I clone MXNet as `git clone --recursive https://github.com/dmlc/mxnet`,is it right?@Oh233
