### ISSUE TITLE
Can I test the model's accuracy right after each epoch on validation set?

### ISSUE THREAD

**Issue by squidszyd** [msracver/Deformable-ConvNets#180]
I've tried to declare an `eval_iter`, which is passed to `fit()`, but since the config is a shared variable, whose `is_train` entry is always `True` during training. However, during evaluation, the module does not require data like `bbox_target` to be given.  Is there a solution here?

**Comment by Oh233** [comment]
One of the solutions is to add an evaluation function inside do_checkpoint. (https://github.com/msracver/Deformable-ConvNets/blob/master/rfcn/core/callback.py) By this way, it will save the snapshot as well as evaluate it after each epoch ends.

**Comment by squidszyd** [comment]
Thanks a lot

**Comment by soumenms2015** [comment]
@squidszyd @Oh233 where did you pass the validation dataset to compute the validation checkpoints.

**Comment by soumenms2015** [comment]
In fit function, I passed the eval_dataiter, but my question, how the .yaml file will be configured accordingly as cfgs/.yaml file has only train and test dataset?

**Comment by squidszyd** [comment]
@soumenms2015 So I just need to construct another `AnchorLoader` and pass it to `fit(...)`

**Comment by soumenms2015** [comment]
@Oh233  I have problem with visualizing deform_conv on my dataset?
