### ISSUE TITLE
gpu_nms.hpp:No such file or directory

### ISSUE THREAD

**Issue by travelerxd** [msracver/Deformable-ConvNets#181]

**Comment by travelerxd** [comment]
Hello, everyone:
    When i was running **python ./rfcn/demo.py** , the terminal shows ".pyxbld/temp.linux-x86_64-2.7/pyrex/nms/gpu_nms.c:568:23: fatal error: gpu_nms.hpp: No such file or directory". 
     Is there anyone meet this issue? How should I handle on this? 
     I am looking forward to your reply.

**Comment by eugenelawrence** [comment]
Have you run the scripts [init.bat](https://github.com/msracver/Deformable-ConvNets/blob/master/init.bat) or [init.sh](https://github.com/msracver/Deformable-ConvNets/blob/master/init.sh) ?

**Comment by travelerxd** [comment]
Yes, i have run **sh init.sh**!
