### ISSUE TITLE
when i train rfcn_dcn on my own datasets, the detected results is good, but

### ISSUE THREAD

**Issue by bitwangdan** [msracver/Deformable-ConvNets#227]
the AP score is very small, almost equals to 0, can someone help me?(I change my dataset to VOC's style)

**Comment by knmac** [comment]
I have the same problem when retraining VOC

**Comment by flishwnag** [comment]
Two possible issue: (1) Did you checked the names of each categories in your dataset to make sure there are no bugs? (2) Did you clean the data cache before testing? If your dataset and the VOC's have the same name (e.g. 2012_test), then the program may load the VOC's groundtruth when assessing your dataset. Just a guess as you did not post your codes.

> the AP score is very small, almost equals to 0, can someone help me?(I change my dataset to VOC's style)
