### ISSUE TITLE
The question of offset

### ISSUE THREAD

**Issue by linquanxu** [msracver/Deformable-ConvNets#23]
Hi, in the deformable convolution, the offset is from the output data of the configured convolution layer. I am curious why you process it in that way rather than add some parameters likely adding weight parameter to deforableconv?

**Comment by Orpine** [comment]
I do not quite understand your question, what is "add some parameters"? You could also treat current implementation as "add some parameters", if we package a Convolution layer and a Deformable Convolution layer into one operator. We choose current implementation for clearness

**Comment by linquanxu** [comment]
Thanks for your reply. I misunderstand it. 
I have another question:
how to initialize the offset（conv layer's weights）such as Contant, Xavier or Gaussian type of FillerParameter based on CAFFE?

**Comment by Oh233** [comment]
The weight of convolution is initialized to 0, use Constant FillerParameter in CAFFE

**Comment by zzw1123** [comment]
@HaozhiQi Why are the weights are initialized to 0 rather than doing Xaiver or Kaiming initialization?

**Comment by mosquitobite** [comment]
> @HaozhiQi Why are the weights initialized to 0 rather than doing Xaiver or Kaiming initialization?

Hi, I have the same question. Have you figured it out?
