### ISSUE TITLE
Question DCNv2 operators

### ISSUE THREAD

**Issue by Google1234** [msracver/Deformable-ConvNets#235]
Thanks for your great work!
"
The efficiency of processing multiple images in a mini-batch is considerably improved.
In the previous operator, S is fixed as 1. In the updated operator, S can be set by the im2col_step parameter, whose default value is min(N, 64). The updated operator is significantly faster than the existing one when the image batch size is large."

Why not fix parameters S=1 ,to Process all inputs simultaneously ?Is it limited to GPU memory?

**Comment by ancientmooner** [comment]
The increased memory by larger S is minor. So it is okay to have larger value of S.

**Comment by nian-liu** [comment]
Hi @Google1234 , I am a newbie to Mxnet, could you tell me how to use the provided DCNv2 operators? I guess I need to copy the code in the DCNv2_op folder into the Mxnet source codes and then recompile the  Mxnet? Could you give me some detailed hints? Thank you.
