### ISSUE TITLE
Active Convolution another CVPR 2017 paper which share the same idea

### ISSUE THREAD

**Issue by gaopeng-eugene** [msracver/Deformable-ConvNets#24]

**Comment by gaopeng-eugene** [comment]
For anyone who are interested in this topic, I recommend another paper Active Convolution: Learning the Shape of Convolution for Image Classification. You can find the caffe implementation by googling.

Best Wishes

**Comment by daijifeng001** [comment]
The paper is put on Arxiv after our paper. Although it looks similar, it has not learned image-specific deformation and did not achieve good results on complex vision tasks (e.g., semantic segmentation and object detection). We would discuss the paper in revision.

**Comment by gaopeng-eugene** [comment]
Yes. I totally agree with what you say. Without your paper, I can't understand this beautiful idea.

Best
