### ISSUE TITLE
How to get features from ROIs?

### ISSUE THREAD

**Issue by chihyaoma** [msracver/Deformable-ConvNets#29]
Hi, 

Thank you for sharing this amazing repo. I would like to use your proposed method to get the features (maps or vectors) from ROIs obtained from RPN. 

Is there any way to do that? If so, can you please kindly guild me through it? For example, pruning the network or directly get activations in the middle of the network. 

Thank you!

**Comment by gd-zhang** [comment]
You need to modify the symbol, refer to ./rfcn/deform_conv_demo.py and ./rfcn/symbol/deform_conv_demo.py. In this demo, we get offset activations directly from the network.

Hope this help

**Comment by chihyaoma** [comment]
Thanks for your quick reply. That does look what I want. I will start to write my own for extracting ROIs features.

**Comment by SiyuanQi** [comment]
If I understand the paper and code correctly, the 7x7 feature for class `c` in the `i`th roi (rois are fed into the network as 4d vectors) is `psroipooled_cls_rois_output[i, c, :, :]`, right?
