### ISSUE TITLE
The question of import

### ISSUE THREAD

**Issue by z-xiuxiu** [msracver/Deformable-ConvNets#30]
When I run the R-FCN demo,  It reports error like this. Can someone give me some help?
![360 17001022113100154](https://cloud.githubusercontent.com/assets/27837384/26618021/eddad82a-460a-11e7-9457-005f5fe6445f.jpg)

**Comment by Orpine** [comment]
please run init.sh first

**Comment by z-xiuxiu** [comment]
I didn't pay attention to this step before. Thank you very much @Orpine
