### ISSUE TITLE
PyTorch version of deformable convolution does not exist

### ISSUE THREAD

**Issue by ghost** [msracver/Deformable-ConvNets#301]
In the description it is written "[04/15/2019] The PyTorch version of deformable convolution operators are available in the [mmdetection codebase](https://github.com/open-mmlab/mmdetection). They are very efficient!"

However, there's nothing with that name over there. Could you please help with that?

**Comment by HaozhiQi** [comment]
check https://github.com/open-mmlab/mmdetection/tree/master/configs/dcn and https://github.com/open-mmlab/mmdetection/tree/master/configs/dcnv2
