### ISSUE TITLE
Deeplab implementation is different

### ISSUE THREAD

**Issue by hondaathma** [msracver/Deformable-ConvNets#33]
@Orpine I just noticed that in your deeplab implementation after  the res5c layer there is no ASPP or atrous convolution . In actual deeplab implementation the shared conv layer(res5c) is followed by 4 atrous convolution layers with varying dilation parameters (namely 4,8,16,24)....Is there any specific reason you chose to instead follow it with fc6 and score layer instead?

**conv_feat** = self.get_resnet_conv(data)
**fc6_bias** = mx.symbol.Variable('fc6_bias', lr_mult=2.0)
**fc6_weight** = mx.symbol.Variable('fc6_weight', lr_mult=1.0)
**fc6** = mx.symbol.Convolution(data=conv_feat, kernel=(1, 1), pad=(0, 0), num_filter=1024, name="fc6", bias=fc6_bias, weight=fc6_weight,workspace=self.workspace)
**relu_fc6** = mx.sym.Activation(data=fc6, act_type='relu', name='relu_fc6')
**score_bias** = mx.symbol.Variable('score_bias', lr_mult=2.0)
**score_weight** = mx.symbol.Variable('score_weight', lr_mult=1.0)
**score** = mx.symbol.Convolution(data=relu_fc6, kernel=(1, 1), pad=(0, 0), num_filter=num_classes, name="score", bias=score_bias,weight=score_weight, workspace=self.workspace)

**Comment by hondaathma** [comment]
I changed your code to include the ASSP layers in this fashion.However the training quickly returns nan loss values and blows up.Could you please tell me what else I need to change.? (I set the lr multipliers to 10 and 20 for weights and biases..setting it to 1 and 2 trains the model but gives low accuracy during test) :
```
 def get_train_symbol(self, num_classes):
        data = mx.symbol.Variable(name="data")
        seg_cls_gt = mx.symbol.Variable(name='label')
        # shared convolutional layers
        conv_feat = self.get_resnet_conv(data)
        ##ASPP LAYERS
        ##changing LR multiplier
        fc1_voc12_c0_w = mx.sym.var('fc1_voc12_c0_weight', lr_mult=10.0,wd_mult=1.0)
        fc1_voc12_c0_b = mx.sym.var('fc1_voc12_c0_bias', lr_mult=20.0,wd_mult=0.0)
        fc1_voc12_c0 = mx.symbol.Convolution(name='fc1_voc12_c0',data=conv_feat,kernel=(3,3),num_filter=num_classes,dilate=6,bias=fc1_voc12_c0_b, weight=fc1_voc12_c0_w,pad=6)

        fc1_voc12_c1_w = mx.sym.var('fc1_voc12_c1_weight', lr_mult=10.0,wd_mult=1.0)
        fc1_voc12_c1_b = mx.sym.var('fc1_voc12_c1_bias', lr_mult=20.0,wd_mult=0.0)
        fc1_voc12_c1 = mx.symbol.Convolution(name='fc1_voc12_c1',data=conv_feat,kernel=(3,3),num_filter=num_classes,dilate=12,bias=fc1_voc12_c1_b, weight=fc1_voc12_c1_w,pad=12)

        fc1_voc12_c2_w = mx.sym.var('fc1_voc12_c2_weight', lr_mult=10.0, wd_mult=1.0)
        fc1_voc12_c2_b = mx.sym.var('fc1_voc12_c2_bias', lr_mult=20.0, wd_mult=0.0)
        fc1_voc12_c2 = mx.symbol.Convolution(name='fc1_voc12_c2',data=conv_feat,kernel=(3,3),num_filter=num_classes,dilate=18,bias=fc1_voc12_c2_b, weight=fc1_voc12_c2_w,pad=18)

        fc1_voc12_c3_w = mx.sym.var('fc1_voc12_c3_weight', lr_mult=10.0, wd_mult=1.0)
        fc1_voc12_c3_b = mx.sym.var('fc1_voc12_c3_bias', lr_mult=20.0, wd_mult=0.0)
        fc1_voc12_c3 = mx.symbol.Convolution(name='fc1_voc12_c3',data=conv_feat,kernel=(3,3),num_filter=num_classes,dilate=24,bias=fc1_voc12_c3_b, weight=fc1_voc12_c3_w,pad=24)

        fc1_voc = fc1_voc12_c0+fc1_voc12_c1+fc1_voc12_c2+fc1_voc12_c3

        upsampling = mx.symbol.Deconvolution(data= fc1_voc, num_filter=num_classes, kernel=(32, 32), stride=(16, 16),num_group=num_classes, no_bias=True, name='upsampling',attr={'lr_mult': '0.0'}, workspace=self.workspace)

        croped_score = mx.symbol.Crop(*[upsampling, data], offset=(8, 8), name='croped_score')
        softmax = mx.symbol.SoftmaxOutput(data=croped_score, label=seg_cls_gt, normalization='valid', multi_output=True,use_ignore=True, ignore_label=255, name="softmax")
        return softmax
```

**Comment by Oh233** [comment]
This is to keep the baseline as simple as possible, which can demonstrate the effect of deformable convolution.
