### ISSUE TITLE
Pretrained model for Deformable Faster R-CNN on MSCOCO

### ISSUE THREAD

**Issue by chihyaoma** [msracver/Deformable-ConvNets#36]
Hi,

Thank you again for sharing this amazing repository. 

I noticed that, although the training scripts are provided for Deformable Faster R-CNN, the pre-trained models for Faster R-CNN and Deformable Faster R-CNN are missing. I can also see that you already have the results of Deformable Faster R-CNN on MS COCO. 

Could you please kindly share the pre-trained model for **Deformable Faster R-CNN (2fc), ResNet-v1-101** with us?

Thank you!

**Comment by yexiguafuqihao** [comment]
It's a nice job to share this good repository . But did someone else encounter such problem when train faster rcnn on either pascal_voc or mscoco?
Traceback (most recent call last):
  File "faster_rcnn/train_end2end.py", line 168, in <module>
    main()
  File "faster_rcnn/train_end2end.py", line 165, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "faster_rcnn/train_end2end.py", line 158, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/home/sogou/Deformable-ConvNets/faster_rcnn/core/module.py", line 994, in fit
    callback(epoch, self.symbol, arg_params, aux_params)
  File "/home/sogou/Deformable-ConvNets/faster_rcnn/core/callback.py", line 51, in _callback
    weight = arg['rfcn_bbox_weight']
KeyError: 'rfcn_bbox_weight'

**Comment by daijifeng001** [comment]
Hi, we have uploaded the Deformable Faster R-CNN  model pre-trained on COCO. It is available within the demo model zip.
