### ISSUE TITLE
Error when testing on the Cityscapes dataset

### ISSUE THREAD

**Issue by Definiter** [msracver/Deformable-ConvNets#37]
I tried to test my trained model on the Cityscapes dataset via following command: 

> python experiments/deeplab/deeplab_test.py --cfg experiments/deeplab/cfgs/deeplab_resnet_v1_101_cityscapes_segmentation_dcn.yaml

However, it gave me this error:

> Traceback (most recent call last):
>   File "experiments/deeplab/deeplab_test.py", line 20, in <module>
>     test.main()
>   File "experiments/deeplab/../../deeplab/test.py", line 99, in main
>     test_deeplab()
>   File "experiments/deeplab/../../deeplab/test.py", line 95, in test_deeplab
>     pred_eval(predictor, test_data, imdb, vis=args.vis, ignore_cache=args.ignore_cache, logger=logger)
>   File "experiments/deeplab/../../deeplab/core/tester.py", line 102, in pred_eval
>     evaluation_results = imdb.evaluate_segmentations(all_segmentation_result)
>   File "experiments/deeplab/../../deeplab/../lib/dataset/cityscape.py", line 182, in evaluate_segmentations
>     info = self._py_evaluate_segmentation()
>   File "experiments/deeplab/../../deeplab/../lib/dataset/cityscape.py", line 241, in _py_evaluate_segmentation
>     seg_pred = np.array(Image.open(res_save_path)).astype('float32')
>   File "/home/haowang/software/miniconda2/lib/python2.7/site-packages/PIL/Image.py", line 2410, in open
>     fp = builtins.open(filename, "rb")
> IOError: [Errno 2] No such file or directory: './output/cityscape/deeplab_resnet_v1_101_cityscapes_segmentation_dcn/leftImg8bit_val/results/frankfurt/frankfurt_000001_059642.png'

I guess there is a bug in ./lib/dataset/cityscape.py, line 179, where 
> if not pred_segmentations:
>     self.write_segmentation_result(pred_segmentations)

should be

> if pred_segmentations:
>     self.write_segmentation_result(pred_segmentations)

**Comment by stupidZZ** [comment]
Yes. That's a bug. The code should be:
```
if not (pred_segmentations is None):
   self.write_segmentation_result(pred_segmentations)
```

Thanks a lot:)
