### ISSUE TITLE
Question about deformable_convolution implementation

### ISSUE THREAD

**Issue by Zardinality** [msracver/Deformable-ConvNets#38]
[Here](https://github.com/msracver/Deformable-ConvNets/blob/master/rfcn/operator_cxx/deformable_convolution-inl.h#L268), `input_offset_dim_ ` was defined as the product of `ishape` from 1 to `offset_shape.ndim()`. I was thinking whether it should be `offset_shape`'s product, since it is used to address offset [here](https://github.com/msracver/Deformable-ConvNets/blob/master/rfcn/operator_cxx/deformable_convolution-inl.h#L129)?

**Comment by Orpine** [comment]
Oh, you are right, here is a stupid mistake, but we always use 1 image per batch so this bug will never trigger, however, if someone use 2 or more images per batch it will cause a fatal error. Thanks a lot!

**Comment by Zardinality** [comment]
Though it's solved I still wonder: `ishape` and `offset_shape` looks totally different for me, no matter how much batch_size is (in fact I think batch_size is kind of marginalized in `ProdShape` from dim 1), so how on earth does `batch_size` has to do here?

**Comment by argman** [comment]
@Zardinality , I am now using your tensorflow deform-conv, does that op solve this problem?

**Comment by Zardinality** [comment]
@argman sure, if you have any questions about my impl, feel free to file an issue or email me

**Comment by argman** [comment]
@Zardinality , ok ,tks!
