### ISSUE TITLE
bugs of RFCN's and Faster RCNN's callback function???

### ISSUE THREAD

**Issue by hzh8311** [msracver/Deformable-ConvNets#40]
It is different between `mx.nd.repeat()` and `mx.nd.tile()`. So does it should be `mx.nd.tile()` instead of `mx.nd.repeat` ?

**Comment by Orpine** [comment]
Thanks for your suggestion, we made a mistake when we publish our faster rcnn code (forgot to replace callback function). Now it has been fixed.
