### ISSUE TITLE
mxnet compile failed

### ISSUE THREAD

**Issue by wait1988** [msracver/Deformable-ConvNets#42]
System configuration:Ubuntu14.04,cuda8,cudnn5
Error info when compiling mxnet: 
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
make: *** [build/src/operator/custom/custom.o] Error 1
Does anyone know how to fix it?

**Comment by Orpine** [comment]
Please use gcc4.9 or higher. I suspect gcc4.8 is too old.

**Comment by ZhengRui** [comment]
I tried gcc5 but still same issue, i guess some dependencies are broken, I can not run `git submodule update` sucessfully.
