### ISSUE TITLE
The channel number of DeformableConvolution layer and corresponding offset layer?

### ISSUE THREAD

**Issue by carrierlxk** [msracver/Deformable-ConvNets#44]
In the provided symbols file resnet_v1_101_rfcn_dcn.py, the channels (filter number) of deformation convolution layer is 512 and the filter number of corresponding offset layer is 72, how to set these two numbers? For example, if I want to construct a  deformation network for cifar10, the filter number of deformation convolution layer should be smaller than 512, should I choose 256 or 128?

**Comment by Oh233** [comment]
The #filter equals to its traditional counterpart and the #filter in the offset layer should be kernel_w x kernel_h x 2 x #deformable_group
