### ISSUE TITLE
NameError: name 'resnet_v2_101_rfcn' is not defined

### ISSUE THREAD

**Issue by miraclewkf** [msracver/Deformable-ConvNets#47]
I want to change the symbol 'resnet_v1_101_rfcn' to another symbol 'resnet_v2_101_rfcn', so I just copy this file and change the name to **resnet_v2_101_rfcn**, besides, I also change the class name to **resnet_v2_101_rfcn**. Then, I change the name and symbol's name of the corresponding .yaml file and run  `python experiments/rfcn/rfcn_end2end_train_test.py --cfg experiments/rfcn/cfgs/resnet_v2_101_coco_trainval_rfcn_dcn_end2end_ohem.yaml`, the error occur: `NameError: name 'resnet_v2_101_rfcn' is not defined`
What should I do?

**Comment by Orpine** [comment]
You need to modify \_\_init\_\_.py

**Comment by xueyoo** [comment]
@miraclewkf  how about the resnet_v2_101_rfcn running? does it running successfully?
