### ISSUE TITLE
How to initialized the deformable conv layer?

### ISSUE THREAD

**Issue by El-H** [msracver/Deformable-ConvNets#53]
Is it initialized from zero or pretrained model?

**Comment by lijuan123** [comment]
it seems that when initialized the model, it add some arg_params, and as for these params, it initialized from zero or random

**Comment by Oh233** [comment]
Deformable Conv layer is initialized from ImageNet pre-trained model. But you should notice the offset layers (which is also output by a convolution) is initialized to zero.

**Comment by El-H** [comment]
@Oh233 So in a network, is Deformable Conv layer initialized just as the Conv layer it replaces?

**Comment by Oh233** [comment]
@El-H  Yes

**Comment by El-H** [comment]
@Oh233 Thanks! And in your paper it is said that the learning rates of offset layers are of beta times the existing layers, so what is the range of beta? Less than 1 or greater?

**Comment by Oh233** [comment]
The paper states: β = 1 by default, and β = 0.01 for the fc layer in Faster R-CNN. You may refer to our code for more detail.

**Comment by El-H** [comment]
Okay!
