### ISSUE TITLE
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

### ISSUE THREAD

**Issue by Ottovonxu** [msracver/Deformable-ConvNets#54]
Hi, I got trouble while running the scripts:
 python experiments/rfcn/rfcn_end2end_train_test.py --cfg experiments/rfcn/cfgs/resnet_v1_101_voc0712_rfcn_dcn_end2end_ohem.yaml

After first epoch, I got:

CNNLogLoss=0.776314,    RCNNL1Loss=0.329874,    
Epoch[0] Batch [9900]   Speed: 4.22 samples/sec Train-RPNAcc=0.942865,  RPNLogLoss=0.154231,    RPNL1Loss=0.071810,     RCNNAcc=0.809554,     RCNNLogLoss=0.773895,    RCNNL1Loss=0.330007,    
Epoch[0] Batch [10000]  Speed: 4.22 samples/sec Train-RPNAcc=0.943149,  RPNLogLoss=0.153486,    RPNL1Loss=0.071483,     RCNNAcc=0.809500,     RCNNLogLoss=0.771593,    RCNNL1Loss=0.329987,    
Traceback (most recent call last):
  File "experiments/rfcn/rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 164, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/rfcn/../../rfcn/train_end2end.py", line 157, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "experiments/rfcn/../../rfcn/core/module.py", line 990, in fit
    self.set_params(arg_params, aux_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/base_module.py", line 651, in set_params
    allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

Would you mind give me a hint?
My computer has single GTX 1080Ti.

**Comment by Orpine** [comment]
We find some compatibility issues in MXNet 0.10, if you  are advance user you could fix them by yourself, otherwise we suggest to use the old version (0.9.5).
