### ISSUE TITLE
Question about the implementation of function deformable_im2col() in deformable_im2col.h

### ISSUE THREAD

**Issue by sccbhxc** [msracver/Deformable-ConvNets#59]
How to understand LOG(FATAL) << "not implemented" in the following code ?
```C++
template <typename DType>
inline void deformable_im2col(mshadow::Stream<cpu>* s,
  const DType* data_im, const DType* data_offset, 
  const TShape& im_shape, const TShape& col_shape, const TShape& kernel_shape,
  const TShape& pad, const TShape& stride, const TShape& dilation, 
  const uint32_t deformable_group, DType* data_col) {
  if (2 == kernel_shape.ndim()) {
	  LOG(FATAL) << "not implemented";
  } else {
	  LOG(FATAL) << "not implemented";
  }
}
```

**Comment by Orpine** [comment]
We do not have CPU implementation by now, if you choose CPU to run it will always trigger "not implemented"

**Comment by arunbuduri** [comment]
I have captured the steps (along with the necessary source code) to run inference in CPU mode here - https://drive.google.com/open?id=1P8vYr9ekWp3NK8_N2bs8sl7jRT39m25I

I have tested this on Windows, Mac, Linux, and Ubuntu.
