### ISSUE TITLE
About the structure of dataset VOC2012

### ISSUE THREAD

**Issue by zhFuECL** [msracver/Deformable-ConvNets#74]
Could you tell me what do you mean by `argumented VOC 2012 annotations/image lists` as I don't know its meaning and even can't find the keywords on VOC 2012 dataset webpage(http://host.robots.ox.ac.uk/pascal/VOC/voc2012/)
> Please download argumented VOC 2012 annotations/image lists, and put the argumented annotations and the argumented train/val lists into:
> 
> ./data/VOCdevkit/VOC2012/SegmentationClass/
> ./data/VOCdevkit/VOC2012/ImageSets/Main/
> , Respectively.

Besides, when I run `python experiments/deeplab/deeplab_train_test.py --cfg experiments/deeplab/cfgs/deeplab_resnet_v1_101_voc12_segmentation_base.yaml`
I had the following error:
> Traceback (most recent call last):
>   File "experiments/deeplab/deeplab_train_test.py", line 21, in <module>
>     train.main()
>   File "experiments/deeplab/../../deeplab/train.py", line 159, in main
>     config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
>   File "experiments/deeplab/../../deeplab/train.py", line 74, in train_net
>     for image_set in image_sets]
>   File "experiments/deeplab/../../deeplab/../lib/utils/load_data.py", line 57, in load_gt_segdb
>     imdb = eval(dataset_name)(image_set_name, root_path, dataset_path, result_path)
>   File "experiments/deeplab/../../deeplab/../lib/dataset/pascal_voc.py", line 51, in __init__
>     self.image_set_index = self.load_image_set_index()
>   File "experiments/deeplab/../../deeplab/../lib/dataset/pascal_voc.py", line 67, in load_image_set_index
>     assert os.path.exists(image_set_index_file), 'Path does not exist: {}'.format(image_set_index_file)
> AssertionError: Path does not exist: ./data/VOCdevkit2012/VOC2012/ImageSets/Main/train_seg.txt

Sorry that I'm not familiar with this dataset, and I really don't know what's going on here. Could you help me?

**Comment by Orpine** [comment]
Please read our README, we already provide its download URL.

**Comment by zhFuECL** [comment]
Thank you! Sorry for my carelessness. 
By the way. The VOCdekit directory should be `./data/VOCdevkit2012/VOC2012` according to the source code.

**Comment by ArsenLuca** [comment]
@zhFuECL Can you open the download URL in OneDrive? I failed. 
So could you please give another download URL such as baidu cloud disk @YuwenXiong ? Thank you
