### ISSUE TITLE
Could DCN be used only by CPU

### ISSUE THREAD

**Issue by jacco09** [msracver/Deformable-ConvNets#75]
i want to run the demo.py(r-fcn) only by CPU，so i want to ask whether it support ONLY-CPU

**Comment by YuwenXiong** [comment]
We didn't write CPU code, so you need to write the CPU code by yourself.

**Comment by arunbuduri** [comment]
I have captured the steps (along with the necessary source code) here to run inference in CPU mode - https://drive.google.com/open?id=1P8vYr9ekWp3NK8_N2bs8sl7jRT39m25I

I have tested this on Windows, Mac, Linux, and Ubuntu.
