### ISSUE TITLE
train error 

### ISSUE THREAD

**Issue by xiaohuizheng** [msracver/Deformable-ConvNets#8]
Thank you for sharing the wonderful work, it is really help.
I encounter problems when training.
AttributeError: 'module' object has no attribute 'DeformableConvolution',why?

**Comment by xinghedyc** [comment]
You may not follow this installation step:
```
Copy operators in ./rfcn/operator_cxx to $(YOUR_MXNET_FOLDER)/src/operator/contrib and recompile MXNet.
```

**Comment by xiaohuizheng** [comment]
@xinghedyc I am sure i do it ,but it still have the error

**Comment by Orpine** [comment]
@xiaohuizheng Please make sure you use the correct mxnet, you can print mxnet.__path__

**Comment by xiaohuizheng** [comment]
@Orpine Thank you very much. I 'm really use the error mxnet

**Comment by miraclewkf** [comment]
What you mean print mxnet.__path__?@Orpine
