### ISSUE TITLE
How to assign weights of the symbol in init function if i incorporate Multiresolution network

### ISSUE THREAD

**Issue by chowkamlee81** [msracver/Deformable-ConvNets#89]
I would like to incorporate Multiresolution network by replicating the same symbol given in deeplab/resnet_v1_101_deeplab.py rather than single resolution but with a downsample img input.

If i incorporate multiresolution, then how to initialize the weights for the new symbol incorporated since the weights of the symbol are initialized via pretrained model. For the new symbol(replica of original symbol given in deeplab/resnet_v1_101_deeplab.py , but with downsampled image), how to initialize weights...Kindly help

**Comment by YuwenXiong** [comment]
deeplab/resnet_v1_101_deeplab.py have a function called `init_weight`, you could initialize new layers weight in this function, by using mxnet's ndarray as numpy way.
