### ISSUE TITLE
Is NNPACK supported for Deformable RFCN inference in CPU mode?

### ISSUE THREAD

**Issue by arunbuduri** [msracver/Deformable-ConvNets#91]
Thanks to Yuwen Xiong, I have CPU mode implemented for Deformable in mxnet. I will hopefully get it submitted to mxnet soon.

I'm running this on Ubuntu 16.04 on Azure NC6 machine (6 Cores, E5-2690v3). Though it has K80 GPU, I'm running it in cpu-only mode. For NNPACK, I followed the instructions in https://mxnet.incubator.apache.org/how_to/nnpack.html 

When running rfcn/demo.py without NNPACK, I'm seeing the following results for CPU mode for COCO.
         testing COCO_test2015_000000000891.jpg 4.4321s
         testing COCO_test2015_000000001669.jpg 4.7265s

I tried rebuilding mxnet with NNPACK but I find the performance to only become worse. 
         testing COCO_test2015_000000000891.jpg 4.8443s
         testing COCO_test2015_000000001669.jpg 5.7752s

Is NNPACK supported for Deformable operators in cpu mode?

**Comment by YuwenXiong** [comment]
I think deformable operators have nothing special. However, from the instruction, NNPACK will work only when no-bias=False and dilate=(1, 1), which is false for res5 conv layer in R-FCN.

**Comment by arunbuduri** [comment]
Thanks for the quick response @YuwenXiong ... is there any way to speed up inference on cpu-only mode?
