### ISSUE TITLE
Is it possible to change batchsize per device for deeplab?

### ISSUE THREAD

**Issue by StOnEGiggity** [msracver/Deformable-ConvNets#92]
When I change config.TRAIN.BATCH_IMAGES to 10 rather than 1, I get one error , Single batch only, so is there any suggestion about how to changing batch_size. I am not familiar with multi-processing.

**Comment by YgRen** [comment]
I have the same problems too. How do you solve it ?  the BATCH_IMAGES is set to 1,GPU resources use less than 4G but my GPU resources is 24G.  my dataset is 240k, so this is difficult for my training.Do you have a good solution? I need it very much. Thank you.

**Comment by StOnEGiggity** [comment]
Hi, It's convenient to change batch_size, the reason set BATCH_IMAGES to 1 is image shape is different in VOC(maybe I remember wrong:) ). There are two steps to do:

1.if your image shape is different, you should do preprocessing(like crop) first.the code is stored in **./lib/utils**.

2.There are several scripts to be changed.You can check **./lib/segmentation**at first and change the code about data loader.
