### ISSUE TITLE
ValueError:zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by Mendel1** [msracver/Deformable-ConvNets#97]
When I try to train the net, the error occurs after several iterations. I don't exactly know what's wrong with it. Could anybody tell me the reason? Thanks very much.

**Comment by YuwenXiong** [comment]
Please check your data loader, make sure data loader can read data correctly.

**Comment by Mendel1** [comment]
@YuwenXiong Thank you very much.Today I have time to check it and find the multiprocess in loader couldn't run correctly on my server.As I couldn't change the version of default python(2.7.6),I change the code to make it work without multiprocess and it works well.
